
$background = rgb(1E1E2E)
$foreground = rgb(28283E)

$background-color-light = rgb(28283E)
$border = rgb(28283E)

$blue = rgb(0087af)


$color0 = rgb(070000)
$color1 = rgb(342326)
$color2 = rgb(0D330D)
$color3 = rgb(A15028)
$color4 = rgb(2F768B)
$color5 = rgb(499A93)
$color6 = rgb(B99862)
$color7 = rgb(F3DCB8)
$color8 = rgb(AA9A81)
$color9 = rgb(462E32)
$color10 = rgb(114411)
$white = rgb(cdd6f4)
$color13 = rgb(61CDC4)
$color14 = rgb(F7CA82)
$color15 = rgb(F3DCB8)

